# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rubick Trainer
email: your-email@domain.com
description: Rubick Trainer is a quiz for Dota 2 that tests your knowledge of hero abilities!
preview_image: http://rubicktrainer.wonderfulfailure.com/images/preview.png
canonical_url: http://rubicktrainer.wonderfulfailure.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
